public enum TokenName {
    NUM_INT,
    NUM_DEC,
    ID,
    NOME_VARIAVEL,
    TEXTO,
    PALAVRAS_RESERVADAS,
    COMENTARIOS,
    OPERADOR_COMPARACAO,
    OPERADOR_ATRIBUICAO,
    OPERADOR_MATEMATICO,
    SIMBOLO,
    NEGACAO,
    CARACTER,
    TOKEN_MAL_FORMADO,
    ESPACO,
    FINAL_LINHA

}
